spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: brobro332
    password: 1234
    driver-class-name: oracle.jdbc.driver.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    kr.co.justforme: debug